version: 1
enabled: true
enabledForRepo: true
organization: nsip-legal-dev
features:
  autonomousDevelopment: true
  codeReview: true
  pullRequests: true
  suggestions: true
  autoAssign: true
security:
  trustedBots:
    - github-copilot[bot]
    - github-copilot-support[bot]
modelPreferences:
  - OpenAI GPT-5
  - Claude Opus 4.1
enabledPaths:
  - src/**/*
  - test/**/*
excludedPaths:
  - node_modules/**/*
  - dist/**/*
settings:
  maxFileSizeKB: 5000
  maxContextLength: 10000
  temperature: 0.7
  style:
    codeStyle: typescript-strict
    documentationStyle: jsdoc
permissions:
  allowWriteAccess: true
  allowCreatePullRequest: true
  allowMerge: false
