name: Copilot Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Copilot"
          git config --global user.email "copilot@github.com"
      
      - name: Enable Copilot
        uses: github/copilot@v1
        with:
          workspace: ${{ github.workspace }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure Repository
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              allow_auto_merge: true,
              allow_merge_commit: true,
              allow_rebase_merge: true,
              allow_squash_merge: true
            })
            
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: null,
              enforce_admins: false,
              restrictions: null,
              allow_force_pushes: true,
              allow_deletions: false
            })
